# Generated by Django 3.2.9 on 2021-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='severity',
            field=models.CharField(blank=True, choices=[('l', 'low'), ('m', 'moderate'), ('h', 'high')], default=None, max_length=1, null=True),
        ),
    ]
