# Generated by Django 3.2.9 on 2021-12-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0002_auto_20211208_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Texts',
            new_name='Text',
        ),
    ]
