# Generated by Django 3.2.9 on 2021-12-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0003_rename_texts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='php/'),
        ),
    ]
