# Generated by Django 3.2.9 on 2021-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
