# Generated by Django 3.2.9 on 2021-12-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0005_auto_20211209_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
