# Generated by Django 3.2.9 on 2021-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0007_alter_text_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='severity',
            field=models.CharField(blank=True, choices=[('l', 'low'), ('m', 'moderate'), ('h', 'high')], max_length=1, null=True),
        ),
    ]
