# Generated by Django 3.2.9 on 2021-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0008_auto_20211209_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.CharField(choices=[('gn', 'General'), ('rm', 'Reminder'), ('th', 'Thought'), ('qt', 'Quote'), ('nt', 'Note')], default='gn', max_length=2),
        ),
    ]
