# Generated by Django 3.2.9 on 2021-12-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0009_auto_20211209_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='user',
            new_name='author',
        ),
    ]
