# Generated by Django 3.2.9 on 2021-12-10 04:03

import django.contrib.auth.models
from django.db import migrations, models
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0010_auto_20211210_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
            bases=(django.views.generic.edit.CreateView, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='author',
            new_name='user',
        ),
    ]
