# Generated by Django 3.2.9 on 2021-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifyapi', '0011_auto_20211210_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AlterField(
            model_name='text',
            name='severity',
            field=models.CharField(blank=True, choices=[('l', 'low'), ('m', 'moderate'), ('h', 'high')], default='l', max_length=1, null=True),
        ),
    ]
